import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "react-hot-toast";
import CustomNavBar from "@/components/navbar/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <CustomNavBar>
          </CustomNavBar>
        <ReduxProvider>
            {children}
            <Toaster
  position="top-center"
  reverseOrder={false}
/>
            </ReduxProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
